# Generated by Django 4.0.4 on 2022-05-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadoc', models.DateTimeField()),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('duracion', models.FloatField()),
            ],
            options={
                'db_table': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ProductoCategorias',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='LineaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linearuta', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LineaRutas',
            },
        ),
        migrations.CreateModel(
            name='Molino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_molino', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Molinos',
            },
        ),
        migrations.CreateModel(
            name='PersonalCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PersonalCategoria',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presupuesto', models.CharField(max_length=100)),
                ('presupuesto_inicial', models.FloatField()),
            ],
            options={
                'db_table': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.categoriaproducto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.proveedor')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('sueldo_hora', models.FloatField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.personalcategoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.equipo')),
                ('linea_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.linearuta')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.actividad')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.equipo')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.etapa')),
                ('fechaZafra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.presupuesto')),
                ('linea_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.linearuta')),
                ('molino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.molino')),
            ],
            options={
                'db_table': 'Ordenes',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechazafra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.presupuesto'),
        ),
    ]
