# Generated by Django 4.0.4 on 2022-05-30 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.CreateModel(
            name='GestionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.FloatField()),
                ('fechaZafra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalModule.proveedor')),
            ],
            options={
                'db_table': 'GestionCompras',
            },
        ),
    ]
