# Generated by Django 4.0.4 on 2022-05-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalModule', '0002_alter_actividad_options_gestioncompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fechaZafra',
        ),
    ]
