# Generated by Django 4.0.4 on 2022-06-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalModule', '0004_actividad_num_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosPersonalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'PermisosPersonalizados',
                'permissions': [('usuario_estandar', 'Usuario estandar'), ('usuario_resumen', 'Usuario con reportes resumidos'), ('usuario_detalle', 'Usuario con reportes detallados')],
            },
        ),
    ]
